name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ libgdal-dev libtiff5-dev cmake git

    - name: Build Google Test
      working-directory: mempa/algorithm/tests
      run: |
        mkdir -p googletest/build
        cd googletest
        cmake ..
        make
        mkdir -p ../../build  # Ensure build directory exists

    - name: Build simulator
      working-directory: mempa/algorithm
      run: make clean && make

    - name: Run tests
      working-directory: mempa/algorithm
      run: ./tests/run_tests.sh