name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ gdal-bin libgdal-dev libtiff5-dev cmake git nlohmann-json3-dev

    - name: Build the main program
      run: |
        make
      working-directory: mempa/algorithm

    - name: Download Mars DEM .tif
      run: |
        mkdir -p mempa/tests
        curl -L https://photojournal.jpl.nasa.gov/tiff/PIA02820.tif -o mars_dem.tif
      working-directory: mempa/algorithm/tests

    - name: Build and run tests
      run: |
        make test
      env:
        PRINT_OUTPUT: "false"
      working-directory: mempa/algorithm

    - name: Clean up
      run: |
        make clean
      working-directory: mempa/algorithm
