name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ libgdal-dev libtiff5-dev libgtest-dev

    - name: Build simulator
      working-directory: mempa/algorithm
      run: make clean && make

    - name: Run tests
      working-directory: mempa/algorithm
      # Replace the old run command with this
      run: make test && ./run_tests --gtest_output=xml:test_results.xml || (cat test_results.xml; exit 1)